import "./globals.css";


export const metadata = {
  title: "Mahmoud Elsony",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
          <link rel="preconnect" href="https://fonts.googleapis.com"/>
          <link rel="preconnect" href="https://fonts.gstatic.com"/>
          <link href="https://fonts.googleapis.com/css2?family=Tajawal:wght@200;300;400;500;700;800;900&display=swap" rel="stylesheet"/>
     
          <link rel="icon" type="image/png" sizes="32x32" href="%PUBLIC_URL%/favicon-32x32.png" />
          <link rel="icon" type="image/png" sizes="16x16" href="%PUBLIC_URL%/favicon-16x16.png" />
          <link rel="icon" type="image/svg+xml" href="%PUBLIC_URL%/favicon.svg" />
          <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico" />
          <link rel="apple-touch-icon" sizes="180x180" href="%PUBLIC_URL%/apple-touch-icon.png" />
          <link rel="manifest" href="%PUBLIC_URL%/site.webmanifest" />
          <meta name="theme-color" content="#ffffff" />
          <meta name="apple-mobile-web-app-status-bar" content="#ffffff" />

      </head>
      <body className={``}>
        {children}
      </body>
    </html>
  );
}
